apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rallly.fullname" . }}
  labels:
    app: {{ include "rallly.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rallly.name" . }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ include "rallly.name" . }}
    spec:
      containers:
        - name: rallly
          image: {{ include "rallly.imageTag" . }}  # Replace with your actual image
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
            - name: NEXT_PUBLIC_APP_VERSION
              value: {{ .Chart.AppVersion | quote }}
            - name: NEXT_PUBLIC_SELF_HOSTED
              value: {{ .Values.selfHosted | quote }}
            - name: SECRET_PASSWORD
              value: {{ .Values.secretPassword | quote }}
            - name: SUPPORT_EMAIL
              value: {{ .Values.supportEmail | quote }}
            - name: NOREPLY_EMAIL
              value: {{ .Values.noReplyEmail | quote }}
            - name: NEXT_PUBLIC_BASE_URL
              value: {{ .Values.baseUrl | quote }}
            - name: SMTP_HOST
              value: "smtpd"
            - name: SMTP_PORT
              value: "25"
            - name: API_SECRET
              value: {{ .Values.apiSecret | quote }}
            - name: S3_BUCKET
              value: {{ .Values.s3Bucket | quote }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3Endpoint | quote }}
            - name: S3_ACCESS_KEY
              value: {{ .Values.s3AccessKey | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.s3SecretKey | quote }}
            - name: S3_REGION
              value: {{ .Values.s3Region | quote}}
            - name: S3_PATH
              value: {{ .Values.s3Path | quote}}
            - name: CRYPTOKEN
              value: {{ .Values.s3Cryptoken  | quote}}
            - name: RALLY_INIT_FROM_S3
              value: {{ .Values.iInitFromS3 | quote }}
            - name: S3_RAY_FILE
              value: {{ .Values.s3RallykFile | quote }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"