{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rallly.fullname" . }}
  labels:
    app: {{ include "rallly.name" . }}
  annotations:
    {{ if .Values.ingress.clusterIssuer -}}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{ end -}}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.host }}
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rallly.fullname" . }}
                port:
                  number: 3000
  {{ if .Values.ingress.clusterIssuer -}}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ include "rallly.fullname" . }}-tls
  {{ end }}
{{ end }}